import { and, eq } from "drizzle-orm";
import { db } from "@/db";
import { contradictions, memories, memoryEvidence, userProfiles } from "@/db/schema";
import { embedDocuments } from "@/lib/voyage";
import type { MemoryType } from "@/lib/memory-types";
import { DEMO_USER_ID } from "@/lib/demo-constants";

/**
 * A demo end-user with a history.
 *
 * Memora is invisible on its first day. Its whole claim is about what happens
 * to knowledge over months — facts superseding other facts, contradictions
 * surfacing, a person becoming legible — and a brand-new project has none of
 * that, so the Playground answers every question with "no memories matched".
 * That is the correct answer and a terrible first impression.
 *
 * So a new project starts with someone already in it. This is not a stub or
 * lorem ipsum: it is a deliberately constructed case where the interesting
 * behaviours are visible in the first thirty seconds —
 *
 *   - a fact that replaced an earlier fact, with the old one still readable
 *     and the reason recorded
 *   - two memories that cannot both be true, left flagged rather than guessed
 *   - a memory extraction kept but marked trivial, still retrievable
 *   - evidence: the sentence each memory was actually learned from
 *   - a profile written from the memories rather than from a template
 *
 * Written by hand rather than generated by running the real pipeline. A demo
 * should tell the same story every time, and 40 extraction calls per signup is
 * a strange thing to pay for.
 */

export { DEMO_USER_ID };

type Seed = {
  content: string;
  type: MemoryType;
  confidence: number;
  importance: number;
  /** Days before now, so the history has shape rather than all landing at once. */
  daysAgo: number;
  /** The sentence this was learned from — what makes a memory auditable. */
  excerpt: string;
  status?: "active" | "stale" | "superseded" | "archived" | "flagged";
  recallCount?: number;
  /** Marks a memory extraction judged not worth much; kept, not deleted. */
  trivial?: boolean;
  /** Links a replacement to the memory it replaced, by `key`. */
  key?: string;
  supersedes?: string;
  supersedeReason?: string;
  /** Flags an unresolved conflict against another memory, by `key`. */
  contradicts?: string;
  contradictionReason?: string;
};

const SEEDS: Seed[] = [
  // --- who she is -----------------------------------------------------------
  {
    key: "role",
    content: "Works at Cloudsmith as a staff engineer on the platform team",
    type: "fact", confidence: 0.94, importance: 0.9, daysAgo: 214, recallCount: 31,
    excerpt: "I just started at Cloudsmith — staff engineer, platform team.",
  },
  {
    content: "Has been writing software for about eleven years",
    type: "fact", confidence: 0.86, importance: 0.6, daysAgo: 210, recallCount: 8,
    excerpt: "I've been doing this about eleven years now, mostly backend.",
  },
  {
    key: "city_old",
    content: "Lives in Porto",
    type: "fact", confidence: 0.9, importance: 0.7, daysAgo: 208, recallCount: 12,
    status: "superseded",
    excerpt: "I'm based in Porto at the moment.",
  },
  {
    content: "Speaks Portuguese and English, and is learning German slowly",
    type: "fact", confidence: 0.8, importance: 0.4, daysAgo: 190, recallCount: 3,
    excerpt: "Portuguese and English fluently. German is a work in progress, emphasis on progress.",
  },

  // --- how she wants to be worked with --------------------------------------
  {
    content: "Prefers short, direct answers with the reasoning available but not upfront",
    type: "preference", confidence: 0.95, importance: 0.85, daysAgo: 201, recallCount: 44,
    excerpt: "Give me the answer first. I'll ask for the why if I need it.",
  },
  {
    content: "Does not want meetings scheduled before 10am",
    type: "preference", confidence: 0.92, importance: 0.7, daysAgo: 176, recallCount: 19,
    excerpt: "Mornings before ten are for deep work. Please stop putting standups there.",
  },
  {
    content: "Always wants code examples in TypeScript rather than JavaScript",
    type: "instruction", confidence: 0.93, importance: 0.75, daysAgo: 168, recallCount: 27,
    excerpt: "If you're showing me code, make it TypeScript. Always.",
  },
  {
    content: "Dislikes being asked to confirm something she has already confirmed",
    type: "preference", confidence: 0.88, importance: 0.6, daysAgo: 121, recallCount: 6,
    excerpt: "I already said yes. Please don't ask me again three messages later.",
  },

  // --- the contradiction ----------------------------------------------------
  // Two statements about the same subject with opposing valence, three months
  // apart, and no way to tell which is current. Both stay readable and flagged;
  // guessing would be worse than saying so.
  {
    key: "postgres_pref",
    content: "Prefers Postgres over any managed NoSQL option for application data",
    type: "preference", confidence: 0.84, importance: 0.65, daysAgo: 154, recallCount: 9,
    status: "flagged",
    excerpt: "Honestly I'd take Postgres over Dynamo for basically anything with relations.",
  },
  {
    content: "Says Postgres is the wrong default and the team should have picked DynamoDB",
    type: "preference", confidence: 0.79, importance: 0.65, daysAgo: 46, recallCount: 4,
    status: "flagged",
    contradicts: "postgres_pref",
    contradictionReason:
      "Both are stated preferences about the same choice with opposite valence, four months apart. " +
      "The later one may be a change of mind or may be frustration during an incident — there is no " +
      "way to tell from the text, so both are surfaced rather than one being silently dropped.",
    excerpt: "Postgres was the wrong call here. We should have gone with Dynamo from day one.",
  },

  // --- the supersede chain --------------------------------------------------
  {
    key: "city_new",
    content: "Lives in Lisbon",
    type: "fact", confidence: 0.93, importance: 0.7, daysAgo: 88, recallCount: 22,
    supersedes: "city_old",
    supersedeReason:
      "Same subject — where she lives — with a later, explicit statement. A move is a change over " +
      "time rather than a conflict, so the earlier memory is superseded and kept readable, not deleted.",
    excerpt: "Finally moved to Lisbon last month. The commute is a train ride now.",
  },

  // --- goals and decisions --------------------------------------------------
  {
    content: "Wants to move the team off a monolith without a rewrite",
    type: "goal", confidence: 0.87, importance: 0.9, daysAgo: 142, recallCount: 17,
    excerpt: "I want to get us off the monolith, but I'm not doing a big-bang rewrite. Strangler fig.",
  },
  {
    content: "Team decided to use pgvector rather than a dedicated vector database",
    type: "decision", confidence: 0.91, importance: 0.7, daysAgo: 133, recallCount: 11,
    excerpt: "We're going with pgvector. One less thing to operate.",
  },
  {
    content: "Decided against Kubernetes for the current scale, revisiting at 20 services",
    type: "decision", confidence: 0.89, importance: 0.65, daysAgo: 97, recallCount: 7,
    excerpt: "No Kubernetes yet. We'll look again when we're past twenty services.",
  },
  {
    content: "Is trying to reduce on-call load for the platform team",
    type: "goal", confidence: 0.85, importance: 0.8, daysAgo: 63, recallCount: 13,
    excerpt: "The on-call load is unsustainable. That's my main thing this quarter.",
  },

  // --- relationships --------------------------------------------------------
  {
    content: "Reports to Daniel, the director of engineering",
    type: "relationship", confidence: 0.9, importance: 0.6, daysAgo: 205, recallCount: 5,
    excerpt: "Daniel's my manager — he's the director of engineering.",
  },
  {
    content: "Works most closely with Tom, who owns the ingestion service",
    type: "relationship", confidence: 0.86, importance: 0.55, daysAgo: 129, recallCount: 9,
    excerpt: "Tom owns ingestion, so we're in each other's PRs constantly.",
  },
  {
    content: "Mentors two junior engineers, Sara and Ade",
    type: "relationship", confidence: 0.83, importance: 0.5, daysAgo: 74, recallCount: 4,
    excerpt: "I've got two juniors I mentor, Sara and Ade.",
  },

  // --- events, the kind that are evidence about something durable -----------
  {
    content: "Deployment on 14 March 2026 failed because of a missing DATABASE_URL",
    type: "event", confidence: 0.88, importance: 0.45, daysAgo: 161, recallCount: 6,
    excerpt: "That deploy blew up on the 14th — missing DATABASE_URL, of course.",
  },
  {
    content: "Ran a postmortem after a four-hour outage caused by connection pool exhaustion",
    type: "event", confidence: 0.9, importance: 0.6, daysAgo: 108, recallCount: 8,
    excerpt: "Four hours down. Connection pool exhaustion. The postmortem was not fun.",
  },
  {
    content: "Is vegetarian and does not eat dairy",
    type: "fact", confidence: 0.82, importance: 0.55, daysAgo: 118, recallCount: 15,
    // An ordinary lunch remark that is significant evidence about a diet — the
    // kind of thing extraction is instructed to keep rather than dismiss.
    excerpt: "I'll skip the cheese board — vegetarian, and dairy doesn't agree with me.",
  },
  {
    content: "Cycles to the office most days",
    type: "context", confidence: 0.74, importance: 0.35, daysAgo: 84, recallCount: 2,
    excerpt: "I bike in most days, it's about twenty minutes.",
  },

  // --- the ones that went stale --------------------------------------------
  {
    content: "Was evaluating Vercel for hosting the internal dashboard",
    type: "context", confidence: 0.5, importance: 0.4, daysAgo: 173, recallCount: 1,
    status: "stale",
    excerpt: "We might put the internal dashboard on Vercel, still looking.",
  },
  {
    content: "Was considering leaving the platform team for the data team",
    type: "context", confidence: 0.45, importance: 0.5, daysAgo: 150, recallCount: 0,
    status: "stale",
    excerpt: "I've wondered about moving over to data, but nothing concrete.",
  },

  // --- kept, but judged trivial --------------------------------------------
  // Not deleted. The decider's judgement is not reliable enough to remove data
  // from retrieval, so the judgement is recorded and the memory stays.
  {
    content: "Said the weather in Lisbon had been unusually warm",
    type: "context", confidence: 0.4, importance: 0.1, daysAgo: 30, recallCount: 0,
    trivial: true,
    excerpt: "It's been ridiculously warm here.",
  },
  {
    content: "Mentioned enjoying a documentary about deep-sea cabling",
    type: "context", confidence: 0.42, importance: 0.15, daysAgo: 21, recallCount: 0,
    trivial: true,
    excerpt: "Watched a doc about undersea cables last night, weirdly gripping.",
  },
];

const PROFILE = `Priya is a staff engineer on Cloudsmith's platform team, roughly eleven years into writing software, now based in Lisbon after moving from Porto earlier this year.

Her working style is explicit and she states it directly: answers first and reasoning on request, code examples in TypeScript, and no meetings before 10am because mornings are for deep work. She dislikes being asked to re-confirm decisions she has already made.

Her current focus is structural rather than feature work — moving the team off the monolith without a rewrite, and bringing down an on-call load she considers unsustainable. Recent architectural calls favour operational simplicity: pgvector over a dedicated vector database, no Kubernetes until the service count justifies it. She works closely with Tom on ingestion, reports to Daniel, and mentors two junior engineers.

One thing is unresolved: she has argued both for Postgres over managed NoSQL and, four months later, that Postgres was the wrong default and DynamoDB should have been chosen. That may be a change of mind or frustration after an outage. It is flagged rather than resolved, because the text does not say which.`;

export type SeedResult = { memories: number; embedded: boolean };

/**
 * Inserts the demo user into a project environment. Idempotent: re-running
 * replaces the demo user's data and leaves every other end-user untouched.
 */
export async function seedDemoUser(scope: {
  projectId: string;
  environmentId: string;
}): Promise<SeedResult> {
  const scoped = and(
    eq(memories.projectId, scope.projectId),
    eq(memories.environmentId, scope.environmentId),
    eq(memories.endUserId, DEMO_USER_ID)
  );
  await db.delete(memories).where(scoped);
  await db
    .delete(userProfiles)
    .where(
      and(
        eq(userProfiles.projectId, scope.projectId),
        eq(userProfiles.environmentId, scope.environmentId),
        eq(userProfiles.endUserId, DEMO_USER_ID)
      )
    );

  // One request for every memory rather than one per memory — Voyage's free
  // tier allows three requests a minute, so a loop here would take a quarter of
  // an hour and a batch takes a second.
  let embeddings: number[][] | null = null;
  try {
    embeddings = await embedDocuments(SEEDS.map((seed) => seed.content));
  } catch {
    // Seeding without embeddings still gives a populated Explorer and working
    // keyword recall; the alternative is a signup that fails because a third
    // party is rate-limiting us.
    embeddings = null;
  }

  const now = Date.now();
  const at = (daysAgo: number) => new Date(now - daysAgo * 24 * 60 * 60 * 1000);

  const inserted = await db
    .insert(memories)
    .values(
      SEEDS.map((seed, index) => ({
        projectId: scope.projectId,
        environmentId: scope.environmentId,
        endUserId: DEMO_USER_ID,
        content: seed.content,
        type: seed.type,
        confidence: seed.confidence,
        importance: seed.importance,
        status: seed.status ?? "active",
        sourceType: "demo",
        embedding: embeddings?.[index] ?? null,
        metadata: seed.trivial ? { discarded: "trivial" } : null,
        createdAt: at(seed.daysAgo),
        updatedAt: at(seed.daysAgo),
        lastConfirmedAt: at(seed.daysAgo),
        // Already judged: a demo should not show every memory as awaiting
        // reconciliation, which is a transient state, not the resting one.
        reconciledAt: at(seed.daysAgo),
        recallCount: seed.recallCount ?? 0,
        lastRecalledAt: seed.recallCount ? at(Math.max(1, Math.floor(seed.daysAgo / 3))) : null,
      }))
    )
    .returning({ id: memories.id, content: memories.content });

  const idFor = (key: string) => {
    const index = SEEDS.findIndex((seed) => seed.key === key);
    return index === -1 ? null : inserted[index].id;
  };

  // The version chain: the replacement points at what it replaced.
  for (const [index, seed] of SEEDS.entries()) {
    if (!seed.supersedes) continue;
    const previous = idFor(seed.supersedes);
    if (previous) {
      await db
        .update(memories)
        .set({ supersedesId: previous })
        .where(eq(memories.id, inserted[index].id));
    }
  }

  await db.insert(memoryEvidence).values(
    SEEDS.map((seed, index) => ({
      memoryId: inserted[index].id,
      sourceType: "demo",
      excerpt: seed.excerpt,
      eventType: seed.supersedes ? ("updated" as const) : ("extracted" as const),
      reasoning: seed.supersedeReason ?? null,
      createdAt: at(seed.daysAgo),
    }))
  );

  for (const [index, seed] of SEEDS.entries()) {
    if (!seed.contradicts) continue;
    const other = idFor(seed.contradicts);
    if (!other) continue;
    await db.insert(contradictions).values({
      projectId: scope.projectId,
      memoryIdA: other,
      memoryIdB: inserted[index].id,
      reasoning: seed.contradictionReason ?? "Conflicting statements about the same subject.",
      detectedAt: at(seed.daysAgo),
    });
  }

  const activeIds = inserted
    .filter((_, index) => (SEEDS[index].status ?? "active") === "active")
    .map((row) => row.id);

  await db.insert(userProfiles).values({
    projectId: scope.projectId,
    environmentId: scope.environmentId,
    endUserId: DEMO_USER_ID,
    content: PROFILE,
    sourceMemoryIds: activeIds,
    memoryCount: activeIds.length,
    generatedAt: at(3),
  });

  return { memories: inserted.length, embedded: embeddings !== null };
}
